---
title: "Whip_PeakSpeed_stat"
author: "Marta Russo"
date: "03/05/2021"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include = FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, comment="",out.height='100%',  eval = TRUE, warning = FALSE)
#fig.height=6, fig.width=10, 
library(ggplot2)
theme_set(theme_grey() + theme(text=element_text(size=12), 
                               axis.title=element_text(size=16), 
                               axis.text=element_text(size=12),
                               legend.title = element_text(size = 12),
                               legend.text=element_text(size=12),
                               #legend.key.size = unit(3,"line"),
                               #legend.title=element_text(size=24),
                               strip.text=element_text(size=16),
                               panel.grid.minor.x = element_blank(),
                               panel.grid.minor.y = element_blank(),
                               #strip.background = element_blank(),
                               #strip.text.x = element_blank()
                               )
          )

library(lme4)
library(plyr)
library(optimx)
library(gridExtra)
library(tidyverse)
#library(lmerTest)
library(RColorBrewer)
library(sjPlot)
nb.cols <- 16
mycolors <- colorRampPalette(brewer.pal(8, "Dark2"))(nb.cols)

#change here!
setwd("~/OneDrive/Documents/StatAnal/WhipProject")


```


## Data 

load data of hand peak speed

```{r}
x <- read.csv("Whip.csv", header =TRUE, sep = ",")
data = subset(x,select=c(Subj,Block,StyleDR, Trial,HS_HSmax, MinDist,HitFlag))
for (i in c(1:length(data$StyleDR))){
  if(data$StyleDR[i] == 1 ){
    data$StyleDR[i] = 'Discrete'
  } else {
    data$StyleDR[i] = 'Rhythmic'
  }
}

#data$Block = as.factor(data$Block)
data$Block = as.numeric(data$Block)

data$StyleDR = as.factor(data$StyleDR)
data$Subj = factor(data$Subj,levels = c("14","10","13","16","6","5","11","4","3","1","8","7","2","15","9","12"))


data$ps = data$HS_HSmax
# dur = aggregate(dur_peak2peak_block ~ StyleDR +Block+ Subj, data = data, median,na.rm=TRUE) 
# durSD = aggregate(dur_peak2peak_block ~ StyleDR +Block+ Subj, data = data, sd,na.rm=TRUE) 
# 
# dur$sd = durSD$dur_peak2peak_block
# dur$dur = dur$dur_peak2peak_block
# dur$CoV = dur$sd/dur$dur
```

#  Linear mixed model on intertrial duration

$PeakSpeed_{ij} = \beta_0 + S_{0i}  + (\beta_{B} + S_{Bi})Block_j + (\beta_{S} + S_{Si})Style_j + \beta_{SB}Block_j Style_j + \epsilon_{ij}$


```{r}

mod0 <- lm(ps ~ StyleDR +Block  , data = data,REML = FALSE)
mod1 <- lmer(ps ~ StyleDR +Block + (1|Subj) , data = data,REML = FALSE)
anova(mod1,mod0)

AIC(mod0)
AIC(mod1)
mod2 <- lmer(ps ~ StyleDR +Block + (1+Block|Subj) , data = data,REML = FALSE)
anova(mod1,mod2)

mod2 <- lmer(ps ~ StyleDR +Block + (1+StyleDR|Subj) , data = data,REML = FALSE)
anova(mod1,mod2)

mod3 <- lmer(ps ~ StyleDR +Block + (1+Block+StyleDR|Subj) , data = data,REML = FALSE)
mod4 <- lmer(ps ~ StyleDR *Block + (1+Block+StyleDR|Subj) , data = data,REML = FALSE)
anova(mod3,mod4)

library(lmerTest)
mod1 <- lmer(ps ~ StyleDR *Block + (1+Block+StyleDR|Subj) , data = data,REML = FALSE)
summary(mod1)

{qqnorm(residuals(mod1,type="deviance"))
qqline(residuals(mod1))}

```

# Plot linear model group by subjects

```{r}
plot_model(
  mod1, 
  type = "pred", 
  terms = c("Block", "StyleDR",'Subj'), 
  colors = c('#fe9d0e','#0f8b8d')
  ,pred.type="re"
)


```

# Plot linear model group by style and subjects

```{r}
plot_model(
  mod1, 
  type = "pred", 
  terms = c("Block", 'Subj','StyleDR'), 
  colors = mycolors
  ,pred.type="re"
)


```

```{r}
#1) Generate a new dataframe
# do not have block as factor to plot
blocks = seq(1, 5, .1)
subj <- levels(data$Subj)
style <- levels(data$StyleDR)
newdfr = expand.grid(style, blocks, subj)
names(newdfr) = c("StyleDR", "Block", "Subj")
newdfr$predict.model.an <- predict(mod1, newdata = newdfr,na.action = na.pass)

MinDist.plot <- ggplot(data, aes(x = Block, y = ps, color= Subj)) +
  ylab("Min Dist (m)") +
  xlab("Block") +
  geom_point() +
  theme(legend.box.margin = margin(6, 6, 6, 6)) +
  #scale_color_manual(values=c('#fe9d0e','#0f8b8d')) +
  scale_x_continuous(breaks=c(1, 2, 3, 4, 5)) +
  geom_line(data = newdfr, aes(x = Block, y = predict.model.an, color = Subj)) +
  facet_wrap(~ StyleDR)

MinDist.plot

```

# Plot linear model on median per subjects, group by style 

```{r}
#datam = aggregate(MinDist ~ StyleDR +Block+ Subj, data = ps, median)

#mod1.m <- lmer(MinDist ~ StyleDR *Block + (1+Block|StyleDR), data = datam, REML = F)
#summary(mod1.m)

#1) Generate a new dataframe
# do not have block as factor to plot
# blocks = seq(1, 5, .1)
# subj <- levels(datam$Subj)
# style <- levels(datam$StyleDR)
# newdfr = expand.grid(style, blocks, subj)
# names(newdfr) = c("StyleDR", "Block", "Subj")
# newdfr$predict.model.an <- predict(mod1.m, newdata = newdfr,na.action = na.pass)
library(tidyverse)
MinDist.plot <- ggplot(data,mapping = aes(x = Block, y = ps,color= StyleDR)) +
  ylab("Min Dist (m)") +
  xlab("Block") +
  geom_point() +
  #theme_bw() +
  scale_color_manual(values=c('#fe9d0e','#0f8b8d')) +
  #scale_x_continuous(breaks=c(1, 2, 3, 4, 5)) +
  geom_smooth( method = 'lm')+
  #geom_line(data = newdfr, aes(x = Block, y = predict.model.an)) +
  facet_wrap(~ StyleDR)

#ggplot(data = mpg) + 
  #geom_smooth(mapping = aes(x = displ, y = hwy, linetype = drv), stat = lm)

MinDist.plot

plot_model(
  mod1, 
  type = "pred", 
  terms = c("Block", 'StyleDR')
  #,group.terms = 'StyleDR'
  ,colors = c('#fe9d0e','#0f8b8d')
  #,pred.type="re"
)


```
